POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "test42@42.com",
    "password": "test without instance"
}


### Find a paritiular user with a given ID
GET http://localhost:3000/auth/5


### Find all users with a given ID
GET http://localhost:3000/auth?email=test42@42.com


### Delete a user with a given ID
DELETE  http://localhost:3000/auth/1



### Update a user
PATCH   http://localhost:3000/auth/3
content-type: application/json

{
    "password": "000000000"
}